name: geotime_classify
channels:
  - defaults
dependencies:
 - python == 3.8
 - pip # for the pip-only deps
 - jupyter # jupyter notebooks
 - jupyterlab # jupyter lab, much nicer notebooks
 - numpy
 - pandas >= 1.0
 - matplotlib
 - scipy # more math
 - scikit-learn #models
 - statsmodels # models
 - matplotlib # plotting
 - psycopg2 #postgres io
 - sqlalchemy # postgres io
 - ipython # interactive terminal
 - pyyaml # YAML IO
 - joblib # easier multiprocessing and a faster pickler
 - h5py # hdf5 file for dynasim aggregation
 - pylint == 2.4.4 # linting, freeze at 2.4.4 as 2.5 gave errors
 - beautifulsoup4 # Web scraping
 - lxml # parser for bs4
 - xarray # SPEI loading
 - numba # For fast stuff
 - pyarrow # For Parquet IO in pandas
 - psutil # For physical core detection, thread's don't help dynasim
 - descartes # Basic Geopandas Plotting
 - xlrd # Dependency pd.read_excel
 - xlwt # For formatting (old) Excel files
 - seaborn # Fancy plotting
 # These packages are only available from pip or have later versions there
 - pip:
   - black # Code formatting
   - coverage # Test coverage report
   - flake8 # Grumpy linter
   - geoalchemy2 # Geometry types for pushing geodataframes to postgres
   - geopandas
   - html5lib # Reign loader bs4 parser
   - libpysal
   - mypy # Type checking
   - netcdf4 # SPEI loading
   - pytest # Testing
   - requests # read the web
   - sphinx # Docs
   - xgboost # pip has later versions than conda
   - contextily
   - pdpbox
